twig_component:
    anonymous_template_directory: 'component/'
    defaults:
        # Namespace & directory for components
        App\Twig\Component\Core\: 'component/core'
        App\Twig\Component\User\: 'component'
        App\Twig\Component\Toy\: 'component'
